name: 'Extend'

on:
  push:
  watch:
    types: started
    branches:
      - main
  schedule:
    - cron: '0 9 * * 6'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3

      - name: 'Set python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4
          python -m pip install --upgrade pyairtable
          python -m pip install -r requirements.txt
      - name: 'Auto_renew'
        env:
          YD_EMAIL: ${{ secrets.YD_EMAIL }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          YD_APP_PWD: ${{ secrets.YD_APP_PWD }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          CUSTOMERIDS: ${{ secrets.CUSTOMERIDS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SERVER_CHAN_SENDKEY: ${{ secrets.SERVER_CHAN_SENDKEY }}
          MAILPARSER_DL_IDS_FOR_LOGIN: ${{ secrets.MAILPARSER_DL_IDS_FOR_LOGIN }}
          MAILPARSER_DL_IDS_FOR_RENEW: ${{ secrets.MAILPARSER_DL_IDS_FOR_RENEW }}

        run: python main.py
